browser: firefox
screenshot_directory: reports/screenshots
screenshot_directory_html: screenshots
env: platform.cinchcast.com
staging_env: https://platform.cinchcast.com/Diagnostics/Utils
intranet: platform.cinchcast.com/intranet
admin_url: platform.cinchcast.com/admin
calling_method: caller
summon_api_env: cb-api.sip.blogtalkradio.com
staging_switch: disabled
video_switch: enabled
env_type: prod
env_prefix: prod