browser: firefox
screenshot_directory: reports/screenshots
screenshot_directory_html: screenshots
env: 
staging_env: 
intranet: 
admin_url: 
calling_method: caller
summon_api_env: 
staging_switch: enabled
video_switch: enabled
env_type: prod
env_prefix: prod
